break test
> android:test-device
[info] testing jp.co.lepidum.mochizuki.apptestbyscala.tests (3 tests)
[error] failed: jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests#testHelloWorldIsShown
[error]
[error] Incomplete: java.lang.IllegalAccessError
[error] testRunFailed: java.lang.IllegalAccessError
[info] testRunEnded (0 seconds)
[trace] Stack trace suppressed: run last tests/android:test-device for the full output.
[error] (tests/android:test-device) Failed tests:
jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests#testHelloWorldIsShown
[error] Total time: 2 s, completed 2012/10/09 11:18:48

$ adb logcat
E/AndroidRuntime(19053): FATAL EXCEPTION: main
E/AndroidRuntime(19053): java.lang.ExceptionInInitializerError
E/AndroidRuntime(19053):        at jp.co.lepidum.mochizuki.apptestbyscala.MainActivity.onCreate(MainActivity.scala:11)
E/AndroidRuntime(19053):        at android.app.Activity.performCreate(Activity.java:4465)
E/AndroidRuntime(19053):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
E/AndroidRuntime(19053):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
E/AndroidRuntime(19053):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
E/AndroidRuntime(19053):        at android.app.ActivityThread.access$600(ActivityThread.java:123)
E/AndroidRuntime(19053):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
E/AndroidRuntime(19053):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19053):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(19053):        at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime(19053):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19053):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19053):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(19053):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(19053):        at dalvik.system.NativeStart.main(NativeMethod)
E/AndroidRuntime(19053): Caused by: java.lang.NoClassDefFoundError:
jp/co/lepidum/mochizuki/apptestbyscala/TypedResource
E/AndroidRuntime(19053):        at jp.co.lepidum.mochizuki.apptestbyscala.TR$.<init>(TR.scala:9)
E/AndroidRuntime(19053):        at jp.co.lepidum.mochizuki.apptestbyscala.TR$.<clinit>(TR.scala)
E/AndroidRuntime(19053):        ... 15 more
E/AndroidRuntime(19053): Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
E/AndroidRuntime(19053):        at dalvik.system.DexFile.defineClass(Native Method)
E/AndroidRuntime(19053):        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:195)
E/AndroidRuntime(19053):        at dalvik.system.DexPathList.findClass(DexPathList.java:315)
E/AndroidRuntime(19053):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:58)
E/AndroidRuntime(19053):        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(19053):        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(19053):        ... 17 more
W/ActivityManager(  192): Error in app
jp.co.lepidum.mochizuki.apptestbyscala running instrumentation
ComponentInfo{jp.co.lepidum.mochizuki.apptestbyscala.tests/android.test.InstrumentationTestRunner}:
W/ActivityManager(  192):   java.lang.IllegalAccessError
W/ActivityManager(  192):   java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

This error is caused by difference of same class definitions in both application apk and test apk.
Before this commit, class definitions of both apks correspond casually in dex format level.
But it is so weak, one line diff brake that.

In the first place test apk should not contain class definitions that be included application apk.
In test context, class loader can load classes from application apk.