remove scala-library.jar from proguard-in-jars
> android:test-device
[info] testing jp.co.lepidum.mochizuki.apptestbyscala.tests (0 tests)
[error] testRunFailed: java.lang.ClassNotFoundException
[info] testRunEnded (0 seconds)
[trace] Stack trace suppressed: run last tests/android:test-device for the
full output.
[error] (tests/android:test-device) java.lang.ClassNotFoundException
[error] Total time: 1 s, completed 2012/10/09 12:43:05

$ adb logcat E/AndroidRuntime(19478): FATAL EXCEPTION: main
E/AndroidRuntime(19478): java.lang.NoClassDefFoundError:
scala/reflect/ScalaSignature
E/AndroidRuntime(19478):        at java.lang.Class.getDeclaredAnnotation(Native Method)
E/AndroidRuntime(19478):        at java.lang.Class.getAnnotation(Class.java:260)
E/AndroidRuntime(19478):        at android.test.suitebuilder.annotation.HasClassAnnotation.apply(HasClassAnnotation.java:39)
E/AndroidRuntime(19478):        at android.test.suitebuilder.annotation.HasClassAnnotation.apply(HasClassAnnotation.java:30)
E/AndroidRuntime(19478):        at com.android.internal.util.Predicates$OrPredicate.apply(Predicates.java:106)
E/AndroidRuntime(19478):        at android.test.suitebuilder.annotation.HasAnnotation.apply(HasAnnotation.java:42)
E/AndroidRuntime(19478):        at android.test.suitebuilder.annotation.HasAnnotation.apply(HasAnnotation.java:31)
E/AndroidRuntime(19478):        at com.android.internal.util.Predicates$NotPredicate.apply(Predicates.java:122)
E/AndroidRuntime(19478):        at android.test.suitebuilder.TestSuiteBuilder.satisfiesAllPredicates(TestSuiteBuilder.java:253)
E/AndroidRuntime(19478):        at android.test.suitebuilder.TestSuiteBuilder.build(TestSuiteBuilder.java:183)
E/AndroidRuntime(19478):        at android.test.InstrumentationTestRunner.onCreate(InstrumentationTestRunner.java:379)
E/AndroidRuntime(19478):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3920)
E/AndroidRuntime(19478):        at android.app.ActivityThread.access$1300(ActivityThread.java:123)
E/AndroidRuntime(19478):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1185)
E/AndroidRuntime(19478):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19478):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(19478):        at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime(19478):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19478):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19478):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(19478):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(19478):        at dalvik.system.NativeStart.main(NativeMethod)
E/AndroidRuntime(19478): Caused by: java.lang.ClassNotFoundException:
scala.reflect.ScalaSignature
E/AndroidRuntime(19478):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(19478):        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(19478):        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(19478):        ... 22 more
D/AndroidRuntime(19468): Shutting down VM
W/ActivityManager(  192): Error in app jp.co.lepidum.mochizuki.apptestbyscala running instrumentation
ComponentInfo{jp.co.lepidum.mochizuki.apptestbyscala.tests/android.test.InstrumentationTestRunner}:
W/ActivityManager(  192):   java.lang.ClassNotFoundException
W/ActivityManager(  192):   java.lang.ClassNotFoundException: scala.reflect.ScalaSignature

As wrote in previous commit message, test apk should not contains scala-library.jar.
But error is caused yet after fix, because ProGuard shrink classes too much.

decompile AndroidTests.class

package jp.co.lepidum.mochizuki.apptestbyscala.tests;
import junit.framework.Assert;
@scala.reflect.ScalaSignature(bytes="\006\001%2A!\001\002\001\037\ta\021I\0343s_&$G+Z:ug*\0211\001B\001\006i\026\034Ho\035\006\003\013\031\ta\"\0319qi\026\034HOY=tG\006d\027M\003\002\b\021\005IQn\\2iSj,8.\033\006\003\023)\tq\001\\3qS\022,XN\003\002\f\031\005\0211m\034\006\002\033\005\021!\016]\002\001'\r\001\001\003\007\t\003#Yi\021A\005\006\003'Q\tA\001^3ti*\tQ#A\004b]\022\024x.\0333\n\005]\021\"aD!oIJ|\027\016\032+fgR\034\025m]3\021\005eaR\"\001\016\013\003m\tQa]2bY\006L!!\b\016\003\027M\033\027\r\\1PE*,7\r\036\005\006?\001!\t\001I\001\007y%t\027\016\036\025\003\005\002\"A\t\001\016\003\tAQ\001\n\001\005\002\025\nA\003^3tiB\0137m[1hK&\0338i\034:sK\016$H#\001\024\021\005e9\023B\001\025\033\005\021)f.\033;")
public class AndroidTests extends android.test.AndroidTestCase implements scala.ScalaObject
{
  public void testPackageIsCorrect()
  {
    Assert.assertEquals("jp.co.lepidum.mochizuki.apptestbyscala", getContext().getPackageName());
  }
}

ScalaSignature contains information for reflection, and ScalaObject is simple marker interface.
It is necesarry for fixing to avoid to shrink these classes by ProGuard.