break test again
> android:test-device
[info] testing jp.co.lepidum.mochizuki.apptestbyscala.tests (3 tests)
[error] failed:jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests#testHelloWorldIsShown
[error]
[error] java.lang.NoClassDefFoundError: jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests$$anonfun$testHelloWorldIsShown$1
[error] at jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests.testHelloWorldIsShown(Tests.scala:20)
[error] at java.lang.reflect.Method.invokeNative(Native Method)
[error] at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
[error] at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
[error] at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
[error] at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
[error] at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
[error] at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)
[error] at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1551)
[info] passed: jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests#testPackageIsCorrect
[trace] Stack trace suppressed: run last tests/android:test-device for the full output.
[error] (tests/android:test-device) Failed tests: jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests#testHelloWorldIsShown
[error] Total time: 2 s, completed 2012/10/10 16:10:44

$ adb logcat W/dalvikvm(23046): Unable to resolve superclass of Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests$$anonfun$testHelloWorldIsShown$1; (33)
W/dalvikvm(23046): Link of class 'Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests$$anonfun$testHelloWorldIsShown$1;' failed
E/dalvikvm(23046): Could not find class 'jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests$$anonfun$testHelloWorldIsShown$1', referenced from method jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests.testHelloWorldIsShown
W/dalvikvm(23046): VFY: unable to resolve new-instance 21 (Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests$$anonfun$testHelloWorldIsShown$1;) in Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests;
D/dalvikvm(23046): VFY: replacing opcode 0x22 at 0x0025
W/dalvikvm(23046): Unable to resolve superclass of Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests$$anonfun$testHelloWorldIsShown$1; (33)
W/dalvikvm(23046): Link of class 'Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests$$anonfun$testHelloWorldIsShown$1;' failed
D/dalvikvm(23046): DexOpt: unable to opt direct call 0x0008 at 0x27 in Ljp/co/lepidum/mochizuki/apptestbyscala/tests/ActivityTests;.testHelloWorldIsShown
I/TestRunner(23046): started:testHelloWorldIsShown(jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests)
I/ActivityManager(  192): START {act=android.intent.action.MAIN flg=0x10000000 cmp=jp.co.lepidum.mochizuki.apptestbyscala/.MainActivity} from pid 23046
D/OpenGLRenderer(12302): Flushing caches (mode 1)
I/ActivityManager(  192): No longer want jp.co.omronsoft.iwnnime.ml (pid 22626): hidden #16
D/OpenGLRenderer(12302): Flushing caches (mode 0)
D/dalvikvm(23046): GC_EXPLICIT freed 245K, 5% free 12721K/13319K, paused 2ms+3ms
D/dalvikvm(23046): GC_EXPLICIT freed 7K, 5% free 12714K/13319K, paused 3ms+3ms
I/TestRunner(23046): failed:testHelloWorldIsShown(jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests)
I/TestRunner(23046): ----- begin exception -----
I/TestRunner(23046):
I/TestRunner(23046): java.lang.NoClassDefFoundError: jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests$$anonfun$testHelloWorldIsShown$1
I/TestRunner(23046):    at jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests.testHelloWorldIsShown(Tests.scala:20)
I/TestRunner(23046):    at java.lang.reflect.Method.invokeNative(NativeMethod)
I/TestRunner(23046):    at java.lang.reflect.Method.invoke(Method.java:511)
I/TestRunner(23046):    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
I/TestRunner(23046):    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
I/TestRunner(23046):    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
I/TestRunner(23046):    at junit.framework.TestCase.runBare(TestCase.java:127)
I/TestRunner(23046):    at junit.framework.TestResult$1.protect(TestResult.java:106)
I/TestRunner(23046):    at junit.framework.TestResult.runProtected(TestResult.java:124)
I/TestRunner(23046):    at junit.framework.TestResult.run(TestResult.java:109)
I/TestRunner(23046):    at junit.framework.TestCase.run(TestCase.java:118)
I/TestRunner(23046):    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:169)
I/TestRunner(23046):    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:154)
I/TestRunner(23046):    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:545)
I/TestRunner(23046):    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1551)
I/TestRunner(23046): ----- end exception -----
I/TestRunner(23046): finished:testHelloWorldIsShown(jp.co.lepidum.mochizuki.apptestbyscala.tests.ActivityTests)
I/TestRunner(23046): started:testAndroidTestCaseSetupProperly(jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests)
I/TestRunner(23046): finished:testAndroidTestCaseSetupProperly(jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests)
I/TestRunner(23046): passed:testAndroidTestCaseSetupProperly(jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests)
I/TestRunner(23046): started:testPackageIsCorrect(jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests)
I/TestRunner(23046): finished:testPackageIsCorrect(jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests)
I/TestRunner(23046): passed:testPackageIsCorrect(jp.co.lepidum.mochizuki.apptestbyscala.tests.AndroidTests)

By previous commit, test apk has loaded classes from application apk.
But classes in application apk is shrinked by ProGuard, this is bad fortest apk.
ProGuard may shrink classes that is needed by test apk.

decompile ActivityTests$$anonfun$testHelloWorldIsShown$1.class

package jp.co.lepidum.mochizuki.apptestbyscala.tests;
import scala.Serializable;
import scala.runtime.AbstractFunction0.mcI.sp;
public final class ActivityTests$$anonfun$testHelloWorldIsShown$1 extends
AbstractFunction0.mcI.sp implements Serializable
{
  public static final long serialVersionUID = 0L;
  public ActivityTests$$anonfun$testHelloWorldIsShown$1(ActivityTests $outer) {}
  public int apply$mcI$sp() { return 0; }
  public final int apply() { return apply$mcI$sp(); }
}

In this case, application apk dosen't contain scala.runtime.AbstractFunction0.mcI.sp that is anonymous function's super class.
In conclusion, we need shrinked scala-library.jar contains all classes that is needed by both application and test.